create table if not exists shipping_tracking_binding (
    id bigint generated by default as identity primary key,
    order_no varchar(128) not null,
    booking_no varchar(128) not null,
    carrier varchar(32) not null default 'MSC',
    enabled boolean not null default true,
    last_status varchar(32),
    last_eta varchar(64),
    last_node varchar(255),
    last_query_time timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_shipping_tracking_binding_order_no unique (order_no),
    constraint uk_shipping_tracking_binding_booking_no unique (booking_no)
);

comment on table shipping_tracking_binding is '海运轨迹绑定关系表';
comment on column shipping_tracking_binding.id is '主键';
comment on column shipping_tracking_binding.order_no is '订单号';
comment on column shipping_tracking_binding.booking_no is '订舱号';
comment on column shipping_tracking_binding.carrier is '船公司，第一版固定 MSC';
comment on column shipping_tracking_binding.enabled is '是否启用';
comment on column shipping_tracking_binding.last_status is '最后查询状态';
comment on column shipping_tracking_binding.last_eta is '最后 ETA';
comment on column shipping_tracking_binding.last_node is '最后节点';
comment on column shipping_tracking_binding.last_query_time is '最后查询时间';
comment on column shipping_tracking_binding.created_at is '创建时间';
comment on column shipping_tracking_binding.updated_at is '更新时间';

create table if not exists shipping_tracking_snapshot (
    id bigint generated by default as identity primary key,
    binding_id bigint not null,
    query_time timestamp with time zone not null,
    status varchar(32) not null,
    events_json clob,
    raw_text clob,
    eta varchar(64),
    latest_node varchar(255),
    screenshot_path varchar(1024),
    error_reason varchar(2048),
    baseline boolean not null default false,
    created_at timestamp with time zone not null,
    constraint fk_shipping_tracking_snapshot_binding foreign key (binding_id) references shipping_tracking_binding (id)
);

comment on table shipping_tracking_snapshot is '海运轨迹查询快照表';
comment on column shipping_tracking_snapshot.id is '主键';
comment on column shipping_tracking_snapshot.binding_id is '绑定ID';
comment on column shipping_tracking_snapshot.query_time is '查询时间';
comment on column shipping_tracking_snapshot.status is '查询状态，SUCCESS / NO_RESULT / FAILED / MANUAL_REQUIRED';
comment on column shipping_tracking_snapshot.events_json is '物流事件前四列 JSON';
comment on column shipping_tracking_snapshot.raw_text is '页面原始可见文本';
comment on column shipping_tracking_snapshot.eta is '预计到港时间';
comment on column shipping_tracking_snapshot.latest_node is '最新节点';
comment on column shipping_tracking_snapshot.screenshot_path is '截图路径';
comment on column shipping_tracking_snapshot.error_reason is '失败原因';
comment on column shipping_tracking_snapshot.baseline is '是否为基线快照';
comment on column shipping_tracking_snapshot.created_at is '创建时间';

create table if not exists shipping_tracking_change_log (
    id bigint generated by default as identity primary key,
    binding_id bigint not null,
    previous_snapshot_id bigint not null,
    current_snapshot_id bigint not null,
    change_type varchar(64) not null,
    change_summary varchar(2048) not null,
    before_json clob,
    after_json clob,
    email_sent boolean not null default false,
    email_sent_time timestamp with time zone,
    created_at timestamp with time zone not null,
    constraint fk_shipping_tracking_change_log_binding foreign key (binding_id) references shipping_tracking_binding (id),
    constraint fk_shipping_tracking_change_log_previous_snapshot foreign key (previous_snapshot_id) references shipping_tracking_snapshot (id),
    constraint fk_shipping_tracking_change_log_current_snapshot foreign key (current_snapshot_id) references shipping_tracking_snapshot (id)
);

comment on table shipping_tracking_change_log is '海运轨迹变化记录表';
comment on column shipping_tracking_change_log.id is '主键';
comment on column shipping_tracking_change_log.binding_id is '绑定ID';
comment on column shipping_tracking_change_log.previous_snapshot_id is '上一份快照ID';
comment on column shipping_tracking_change_log.current_snapshot_id is '当前快照ID';
comment on column shipping_tracking_change_log.change_type is '变化类型';
comment on column shipping_tracking_change_log.change_summary is '变化摘要';
comment on column shipping_tracking_change_log.before_json is '变更前 JSON';
comment on column shipping_tracking_change_log.after_json is '变更后 JSON';
comment on column shipping_tracking_change_log.email_sent is '是否已发送邮件';
comment on column shipping_tracking_change_log.email_sent_time is '邮件发送时间';
comment on column shipping_tracking_change_log.created_at is '创建时间';

create table if not exists shipping_tracking_notification_account (
    id bigint generated by default as identity primary key,
    email varchar(200) not null,
    smtp_password varchar(300) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_shipping_tracking_notification_account_email unique (email)
);

comment on table shipping_tracking_notification_account is '通知邮箱账号表（邮箱 + SMTP 授权码，自己给自己发）';
comment on column shipping_tracking_notification_account.id is '主键';
comment on column shipping_tracking_notification_account.email is '邮箱（同时作为 From 和 To）';
comment on column shipping_tracking_notification_account.smtp_password is 'SMTP 授权码（明文存储，请勿在公网无 TLS 环境暴露 H2 文件）';
comment on column shipping_tracking_notification_account.enabled is '是否启用';
comment on column shipping_tracking_notification_account.created_at is '创建时间';
comment on column shipping_tracking_notification_account.updated_at is '更新时间';
